### ISSUE TITLE
PasswordType is not working with Python 3.8

### ISSUE THREAD

**Issue by khattat** [kvesteri/sqlalchemy-utils#404]
PasswordType imports Passlib's LazyCryptContext which gets failed in Python 3.8.
It gives the following error.
`from time import clock as timer`
`ImportError: cannot import name 'clock' from 'time' (unknown location)`

**Comment by heckad** [comment]
Hello @khattat! Can you provide stack trace?

**Comment by kurtmckee** [comment]
Closing due to age.
